vscode:
  extensions:
    - astro-build.astro-vscode
    - sourcegraph.cody-ai

tasks:
  - init: |
      npm i -g wrangler
      echo 'KEYSTATIC=true' > .env
      echo 'Run the following commands to start dev server:\n1. corepack enable\n2. pnpm install\n3. pnpm run dev'
