vscode:
  extensions:
    - astro-build.astro-vscode
    - sourcegraph.cody-ai

tasks:
  - init: |
      npm i -g wrangler
      echo 'KEYSTATIC=true' > .env
      echo 'Run the following commands to start dev server: 1. corepack enable 2. pnpm install 3. pnpm run dev'
